const Generation6Types = [
  {
    "key": "normal",
    "label": "Normal",
    "matchups": {
      "normal": 1,
      "fire": 1,
      "water": 1,
      "electric": 1,
      "grass": 1,
      "ice": 1,
      "fighting": 1,
      "poison": 1,
      "ground": 1,
      "flying": 1,
      "psychic": 1,
      "bug": 1,
      "rock": 0.5,
      "ghost": 0,
      "dragon": 1,
      "dark": 1,
      "steel": 0.5,
      "fairy": 1,
    }
  },
  {
    "key": "fire",
    "label": "Fire",
    "matchups": {
      "normal": 1,
      "fire": 0.5,
      "water": 0.5,
      "electric": 1,
      "grass": 2,
      "ice": 2,
      "fighting": 1,
      "poison": 1,
      "ground": 1,
      "flying": 1,
      "psychic": 1,
      "bug": 2,
      "rock": 0.5,
      "ghost": 1,
      "dragon": 0.5,
      "dark": 1,
      "steel": 2,
      "fairy": 1,
    }
  },
  {
    "key": "water",
    "label": "Water",
    "matchups": {
      "normal": 1,
      "fire": 2,
      "water": 0.5,
      "electric": 1,
      "grass": 0.5,
      "ice": 1,
      "fighting": 1,
      "poison": 1,
      "ground": 2,
      "flying": 1,
      "psychic": 1,
      "bug": 1,
      "rock": 2,
      "ghost": 1,
      "dragon": 0.5,
      "dark": 1,
      "steel": 1,
      "fairy": 1,
    }
  },
  {
    "key": "electric",
    "label": "Electric",
    "matchups": {
      "normal": 1,
      "fire": 1,
      "water": 2,
      "electric": 0.5,
      "grass": 0.5,
      "ice": 1,
      "fighting": 1,
      "poison": 1,
      "ground": 0,
      "flying": 2,
      "psychic": 1,
      "bug": 1,
      "rock": 1,
      "ghost": 1,
      "dragon": 0.5,
      "dark": 1,
      "steel": 1,
      "fairy": 1,
    }
  },
  {
    "key": "grass",
    "label": "Grass",
    "matchups": {
      "normal": 1,
      "fire": 0.5,
      "water": 2,
      "electric": 1,
      "grass": 0.5,
      "ice": 1,
      "fighting": 1,
      "poison": 0.5,
      "ground": 2,
      "flying": 0.5,
      "psychic": 1,
      "bug": 0.5,
      "rock": 2,
      "ghost": 1,
      "dragon": 0.5,
      "dark": 1,
      "steel": 0.5,
      "fairy": 1,
    }
  },
  {
    "key": "ice",
    "label": "Ice",
    "matchups": {
      "normal": 1,
      "fire": 0.5,
      "water": 0.5,
      "electric": 1,
      "grass": 2,
      "ice": 0.5,
      "fighting": 1,
      "poison": 1,
      "ground": 2,
      "flying": 2,
      "psychic": 1,
      "bug": 1,
      "rock": 1,
      "ghost": 1,
      "dragon": 2,
      "dark": 1,
      "steel": 0.5,
      "fairy": 1,
    }
  },
  {
    "key": "fighting",
    "label": "Fighting",
    "matchups": {
      "normal": 1,
      "fire": 2,
      "water": 1,
      "electric": 1,
      "grass": 1,
      "ice": 2,
      "fighting": 1,
      "poison": 0.5,
      "ground": 1,
      "flying": 0.5,
      "psychic": 0.5,
      "bug": 0.5,
      "rock": 2,
      "ghost": 0,
      "dragon": 1,
      "dark": 2,
      "steel": 2,
      "fairy": 0.5,
    }
  },
  {
    "key": "poison",
    "label": "Poison",
    "matchups": {
      "normal": 1,
      "fire": 1,
      "water": 1,
      "electric": 1,
      "grass": 2,
      "ice": 1,
      "fighting": 1,
      "poison": 0.5,
      "ground": 0.5,
      "flying": 1,
      "psychic": 1,
      "bug": 1,
      "rock": 0.5,
      "ghost": 0.5,
      "dragon": 1,
      "dark": 1,
      "steel": 0,
      "fairy": 2,
    }
  },
  {
    "key": "ground",
    "label": "Ground",
    "matchups": {
      "normal": 1,
      "fire": 2,
      "water": 1,
      "electric": 2,
      "grass": 0.5,
      "ice": 1,
      "fighting": 1,
      "poison": 2,
      "ground": 1,
      "flying": 0,
      "psychic": 1,
      "bug": 0.5,
      "rock": 2,
      "ghost": 1,
      "dragon": 1,
      "dark": 1,
      "steel": 2,
      "fairy": 1,
    }
  },
  {
    "key": "flying",
    "label": "Flying",
    "matchups": {
      "normal": 1,
      "fire": 1,
      "water": 1,
      "electric": 0.5,
      "grass": 2,
      "ice": 1,
      "fighting": 2,
      "poison": 1,
      "ground": 1,
      "flying": 1,
      "psychic": 1,
      "bug": 2,
      "rock": 0.5,
      "ghost": 1,
      "dragon": 1,
      "dark": 1,
      "steel": 0.5,
      "fairy": 1,
    }
  },
  {
    "key": "psychic",
    "label": "Psychic",
    "matchups": {
      "normal": 1,
      "fire": 1,
      "water": 1,
      "electric": 1,
      "grass": 1,
      "ice": 1,
      "fighting": 2,
      "poison": 2,
      "ground": 1,
      "flying": 1,
      "psychic": 0.5,
      "bug": 1,
      "rock": 1,
      "ghost": 1,
      "dragon": 1,
      "dark": 0,
      "steel": 0.5,
      "fairy": 1,
    }
  },
  {
    "key": "bug",
    "label": "Bug",
    "matchups": {
      "normal": 1,
      "fire": 0.5,
      "water": 1,
      "electric": 1,
      "grass": 2,
      "ice": 1,
      "fighting": 0.5,
      "poison": 0.5,
      "ground": 1,
      "flying": 0.5,
      "psychic": 2,
      "bug": 1,
      "rock": 1,
      "ghost": 0.5,
      "dragon": 1,
      "dark": 2,
      "steel": 0.5,
      "fairy": 0.5,
    }
  },
  {
    "key": "rock",
    "label": "Rock",
    "matchups": {
      "normal": 1,
      "fire": 2,
      "water": 1,
      "electric": 1,
      "grass": 1,
      "ice": 2,
      "fighting": 0.5,
      "poison": 1,
      "ground": 0.5,
      "flying": 2,
      "psychic": 1,
      "bug": 2,
      "rock": 1,
      "ghost": 1,
      "dragon": 1,
      "dark": 1,
      "steel": 0.5,
      "fairy": 1,
    }
  },
  {
    "key": "ghost",
    "label": "Ghost",
    "matchups": {
      "normal": 0,
      "fire": 1,
      "water": 1,
      "electric": 1,
      "grass": 1,
      "ice": 1,
      "fighting": 1,
      "poison": 1,
      "ground": 1,
      "flying": 1,
      "psychic": 2,
      "bug": 1,
      "rock": 1,
      "ghost": 2,
      "dragon": 1,
      "dark": 0.5,
      "steel": 1,
      "fairy": 1,
    }
  },
  {
    "key": "dragon",
    "label": "Dragon",
    "matchups": {
      "normal": 1,
      "fire": 1,
      "water": 1,
      "electric": 1,
      "grass": 1,
      "ice": 1,
      "fighting": 1,
      "poison": 1,
      "ground": 1,
      "flying": 1,
      "psychic": 1,
      "bug": 1,
      "rock": 1,
      "ghost": 1,
      "dragon": 2,
      "dark": 1,
      "steel": 0.5,
      "fairy": 0,
    }
  },
  {
    "key": "dark",
    "label": "Dark",
    "matchups": {
      "normal": 1,
      "fire": 1,
      "water": 1,
      "electric": 1,
      "grass": 1,
      "ice": 1,
      "fighting": 0.5,
      "poison": 1,
      "ground": 1,
      "flying": 1,
      "psychic": 2,
      "bug": 1,
      "rock": 1,
      "ghost": 2,
      "dragon": 1,
      "dark": 0.5,
      "steel": 1,
      "fairy": 0.5,
    }
  },
  {
    "key": "steel",
    "label": "Steel",
    "matchups": {
      "normal": 1,
      "fire": 0.5,
      "water": 0.5,
      "electric": 0.5,
      "grass": 1,
      "ice": 2,
      "fighting": 1,
      "poison": 1,
      "ground": 1,
      "flying": 1,
      "psychic": 1,
      "bug": 1,
      "rock": 2,
      "ghost": 1,
      "dragon": 1,
      "dark": 1,
      "steel": 0.5,
      "fairy": 2,
    }
  },
  {
    "key": "fairy",
    "label": "Fairy",
    "matchups": {
      "normal": 1,
      "fire": 0.5,
      "water": 1,
      "electric": 1,
      "grass": 1,
      "ice": 1,
      "fighting": 2,
      "poison": 0.5,
      "ground": 1,
      "flying": 1,
      "psychic": 1,
      "bug": 1,
      "rock": 1,
      "ghost": 1,
      "dragon": 2,
      "dark": 2,
      "steel": 0.5,
      "fairy": 1,
    }
  }
];

export default Generation6Types;
